language: elixir
elixir: # Latest version of Elixir
  - 1.9.1
addons: # ensure that Travis-CI provisions a DB for our test:
  postgresql: '10.10'
services:
  - postgresql
before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate
env:
  - MIX_ENV=test
script: # run the tests:
  - mix test
